scanomatic/ui_server/calibration_api.py
scanomatic/ui_server/general.py
scanomatic/ui_server/test/test_general.py

This is a partial fix to the problem of how the api gave status-code 200 on gracefully refusing or failing requests. It will now give reasonable status-code for the example end-point. Then all other endpoints need updating once agreed that this is nice way.

Abort responses

---

.gitignore

The tests of the calibration didn't previously clean up after themselves, creating files under `/data/config/ccc` that could possibly have conflicted with user data. Sometime before today this was fixed by setting the the `ccc_path` attribute of the `Path` singleton in the tests to a tmp folder. Git blame says that this was accomplished by @local-minimum on 2017-09-06.
This pull request merely updates the `.gitignore` file to acknowledge that his has been resolved.

removec /data/config/ccc from .gitignore

---

Dockerfile

The file that needs this (custom xml-writer) should be removed in the future, but for now, this is needed for the analysis not to crash.

Fixed missing installation

---

scanomatic/image_analysis/grid.py
scanomatic/image_analysis/grid_array.py
scanomatic/image_analysis/test/conftest.py
scanomatic/image_analysis/test/test_grid.py
scanomatic/image_analysis/test/test_grid_array.py
tox.ini

One of the grid functions could attempt mean of an empty slice. Fixed so it now treats this as a gridding failure. Unfortunately the function was used by a function that was used by a ... you get it. So I needed logic to all those functions and tests for those too.
Many for all the different functions involved.
Some of them are a bit weird in what they test for lack of more direct signs of failing grid detection.
Also fixed `tox.ini`
Also some test using the hard image, could start to fail if we improve the gridding because the hard image isn't impossible, but then we just need a new harder/impossible fixture image.
```
/usr/local/lib/python2.7/dist-packages/scanomatic/image_analysis/grid.py:278: RuntimeWarning: Mean of empty slice.
deltas < expected_delta * (1 + leeway))].mean()
```

Runtime warning grid empty mean

---

scanomatic/image_analysis/first_pass_image.py
scanomatic/image_analysis/grayscale.py
scanomatic/image_analysis/image_grayscale.py
scanomatic/image_analysis/signal.py
scanomatic/image_analysis/test/test_signal.py
scanomatic/util/analysis.py

It is hard to know exactly what caused the problem, but the contents of this merge ensures that if no spikes where found or if no deltas were finite, the function should fail gracefully and the failing should be handled correctly.
In attempting to recreate this, a side effect error of the original case with producing grid images when some of the expected data was missing occurred. This is also included in this PR.
Added tests for the function `scanomatic.image_analysis.signal.get_signal_edges` that hopefully captures both the scenario of having useful signal and having at least two kinds of bad signal.
```
Process RpcJob-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File …
```

Bug: No or bad signal in grayscale detection mishandled

---

scanomatic/image_analysis/grid_array.py
scanomatic/image_analysis/test/test_grid_array.py

Assuming that the traceback originated in the `_get_image_slice` method, this PR adds some more checks inside the method.
Testing a whole lot of different parameter setting combinations and making sure the method can handle it..
Because of things, traceback was incomplete.
```
2017-10-17 10:48:17 -- INFO	**Grid Array** Processing [0, 0], index 0
Process RpcJob-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/local/lib/python2.7/dist-packages/scanomatic/server/rpcjob.py", line 115, in run
effector_iterator.next()
File "/usr/local/lib/python2.7/dist-packages/scanomatic/server/analysis_effector.py", line 122, in next
if not self._analyze_image():
File …
```

Unknown error

---

.travis.yml
docker-compose.override.yml
docker-compose.yml
tests/system/test_home.py
tox.ini

This sets up system testing in tox and travis and add a simple selenium test that just checks that the home page title contains "Scan-o-Matic".
I also split the tox config and moved jasmine to a separate environment. That way you can run only jasmine tests or only python tests. Running just `tox` will still run all tests (i.e. in travis).

First selenium test

---

karma.conf.js
package.json
scanomatic/ui_server_data/CCC.html
scanomatic/ui_server_data/js/ccc/Blob.js
scanomatic/ui_server_data/js/ccc/api.js
scanomatic/ui_server_data/js/ccc/components/ColonyEditor.js
scanomatic/ui_server_data/js/ccc/components/ColonyFeatures.js
scanomatic/ui_server_data/js/ccc/components/ColonyImage.js
scanomatic/ui_server_data/js/ccc/containers/ColonyEditorContainer.js
scanomatic/ui_server_data/js/ccc/helpers.js
scanomatic/ui_server_data/js/ccc/index.js
scanomatic/ui_server_data/js/ccc/scope.js
scanomatic/ui_server_data/js/specs/components/ColonyEditor.spec.js
scanomatic/ui_server_data/js/specs/components/ColonyFeatures.spec.js
scanomatic/ui_server_data/js/specs/components/ColonyImage.spec.js
scanomatic/ui_server_data/js/specs/components/enzyme-setup.js
scanomatic/ui_server_data/js/specs/containers/ColonyEditorContainer.spec.js
scanomatic/ui_server_data/js/specs/fixtures/colonyData.json
webpack.config.js

"Fix" by refactoring the colony editor (for lack of a better name) to a react component.
Instead of storing the current colony data in the `scope` object, it uses local component state and doesn't have the reported problem.
Try to keep the UI mostly the same (DOM structure, styles) and reused most of the helper code (API and canvas manipulation).
Add test for the re-factored interaction (corresponding roughly to the removed jquery code) but not the re-used code (API and canvas drawing).

Fix issue where "setting" a colony without background would lose the `scope`.

---

scanomatic/ui_server_data/CCC.html
scanomatic/ui_server_data/js/ccc/api.js
scanomatic/ui_server_data/js/ccc/components/ColonyEditor.js
scanomatic/ui_server_data/js/ccc/containers/ColonyEditorContainer.js
scanomatic/ui_server_data/js/specs/api.spec.js
scanomatic/ui_server_data/js/specs/components/ColonyEditor.spec.js
scanomatic/ui_server_data/js/specs/containers/ColonyEditorContainer.spec.js

Cell count needs to be set and a positive number to be able to "Set" the
colony.
If there is no cell count when pressing set, or if the cell count is
negative, it gets the bootstrap class "has-error".

Add an <input /> for the cell count in the CCC Colony Editor

---

.babelrc
.gitignore
.travis.yml
karma.conf.js
package.json
webpack.config.js

Generate coverage report for the javascript tests and send to coveralls.
It's a tad convoluted: you need to generate the javascript coverage in the lcov file format, convert it to coveralls' json format using a ruby script and then pass this file to the python coveralls client that merges it with the python coverage.

Javascript coverage

---

scanomatic/ui_server_data/js/ccc/components/ColonyFeatures.js
scanomatic/ui_server_data/js/ccc/helpers.js
scanomatic/ui_server_data/js/specs/helpers.spec.js

By popular demand, here are two changes to the way colony features are visualized:
- use a better (I hope) color palette. The new color are two extremes plus middle values from the viridis color map in matplotlib.
- derive the color used in the legend from the actual rgb value so that there is no discrepancy
Here is how it looks, first the wrong features returned by the API that shows the "neither" color, then the "fixed" features:
(Note that this revealed some artifacts that appear when turning the circle shape into a pixel array. I'm guessing they were already there before but less visible. But maybe it's a feature ;o))

Fix feature colors

---

package.json

One can run eslint with `npm run lint`. It only lints files in `js/ccc` and `js/specs` by default.

Add eslint and a 'lint' script to packgage.json

---

scanomatic/ui_server/calibration_api.py
scanomatic/ui_server/test/test_calibration_api.py

This makes the ccc colony detection actually detect colonies. Restructured some to be easier to test. Though the two non-endpoint function would be better placed in `data_processing/calibration.py`, placing them there would cause circular import and thus they are kept here for now and it would be better dealt with in another PR to do a  bit of restructuring since that file is a bit too large as it is anyhow.

Fixed bug in colony detection

---

scanomatic/ui_server_data/js/ccc/api.js
scanomatic/ui_server_data/js/ccc/components/CCCEditor.js
scanomatic/ui_server_data/js/ccc/components/FinalizedCCC.jsx
scanomatic/ui_server_data/js/ccc/components/PolynomialConstruction.js
scanomatic/ui_server_data/js/ccc/components/Root.jsx
scanomatic/ui_server_data/js/ccc/containers/CCCEditorContainer.js
scanomatic/ui_server_data/js/ccc/containers/PolynomialConstructionContainer.js
scanomatic/ui_server_data/js/ccc/containers/RootContainer.jsx
scanomatic/ui_server_data/js/specs/api.spec.js
scanomatic/ui_server_data/js/specs/components/CCCEditor.spec.js
scanomatic/ui_server_data/js/specs/components/FinalizedCCC.spec.jsx
scanomatic/ui_server_data/js/specs/components/PolynomialConstruction.spec.js
scanomatic/ui_server_data/js/specs/components/Root.spec.jsx
scanomatic/ui_server_data/js/specs/containers/CCCEditorContainer.spec.js
scanomatic/ui_server_data/js/specs/containers/PolynomialConstructionContainer.spec.js
scanomatic/ui_server_data/js/specs/containers/RootContainer.spec.jsx

The finalize button is placed next to the construct button and enabled only if there's a polynomial.
Add a simple component that replaces the CCCEditor when the CCC is finalized.

Add a button to finalize CCC

---

scanomatic/data_processing/calibration.py
scanomatic/data_processing/test/test_calibration.py
scanomatic/ui_server/test/test_calibration_api.py

It isn't physically reasonable that any of the coefficients may become negative, so the solver should not allow for this. Unfortunately I didn't find any way to limit search space for the coefficients in the `optimize.leastsq` so I did manual assurance making both the poly and the results are always positive. Reason it is needed in both is that the solver may overstep into negative coeffs, thinking it is actually using them an thus reporting them as negative while they were actually positive. 
Another way to do the same thing would have been to optimize not on the coefficients but the log of the coefficients, but I think that code may turn a bit more obscure.
I added tests also for surrounding methods that didn't have particular unit tests.

Improving calibration poly guessing and tests of related functions

---

tox.ini

I find the coverage table to be a bit too big and not that useful, especially with coveralls keeping track.

Don't print coverage information in the terminal

---

.gitignore
requirements.in
requirements.txt
scanomatic/io/scanstore.py
scanomatic/models/scan.py
scanomatic/ui_server/experiment_api.py
scanomatic/ui_server/resources.py
scanomatic/ui_server/ui_server.py
tests/system/conftest.py
tests/system/docker-compose.override.yml
tests/system/test_scanner_api.py
tests/unit/io/test_scanstore.py
tests/unit/ui_server/test_experiment_api.py
tox.ini

Add a new endpoint `/api/scans` to post scans (images). The scans are saved in the project directory according to the current file pattern.
I couldn't identify a clear pattern in the design of the current API endpoints so I designed the new endpoint as a REST API because we are already using it at molflow for other projects and there is plenty of resources and tools for it. I suggest that future endpoint should also use REST.
There is already code in Scan-o-Matic that saves scan images. I did try to refactor this to use the same code as the new endpoint but the image-saving code is quite entangled in the scanning "effector" which proved quite painful to get under tests. Or understand.

Image upload endpoint

---

.travis.yml

Tried manually monitoring the travis progress and the test that previous sometimes took more than 10 minutes according to travis now took roughly 2-3minutes. Could be a coincidence, but at least a positive indication.

Invert stages hoping first tox system test will run faster

---

scanomatic/io/scanning_store.py
scanomatic/models/scanjob.py
scanomatic/ui_server/scan_jobs_api.py
scanomatic/ui_server/scanners_api.py
scanomatic/ui_server/serialization.py
scanomatic/ui_server_data/js/specs/api.spec.js
scanomatic/ui_server_data/js/src/api.js
tests/unit/io/test_scanning_store.py
tests/unit/models/test_scanjob.py
tests/unit/ui_server/test_scan_jobs_api.py
tests/unit/ui_server/test_scanners_api.py

Add an API endpoint at `/scanners/ID/job` to get a scanner's current job.
Adds a start time to the `ScanJob` model and refactor both the model and it's json representation to simplify time interval serialization.

Scanner job API

---

scanomatic/io/scanning_store.py
scanomatic/models/scanjob.py
scanomatic/ui_server/scan_jobs_api.py
scanomatic/ui_server/serialization.py
tests/unit/io/test_scanning_store.py
tests/unit/models/test_scanjob.py
tests/unit/ui_server/test_scan_jobs_api.py
tests/unit/ui_server/test_scanners_api.py
tox.ini

Add the following endpoints:
- `GET /api/scan-jobs/$id`: get a single scanjob by id
- `POST /api/scan-jobs/$id/start`: start a scanjob
In REST slang the first would be a document resource and the second a controller resource.
I'm a bit unhappy with the "start" controller having the same name as the "start" (time) field but I'm not sure it's really a problem. I can rename the field if someone thing it's going to cause issues.
This somewhat encroaches on a future task (start job when button is clicked), but I need it to write tests using the scanjob API.

Add `/start` endpoint for scan jobs

---

requirements.in
requirements.txt
scanomatic/io/imagestore.py
scanomatic/ui_server/scans_api.py
scanomatic/util/scanid.py
tests/integration/api/test_scans.py
tests/unit/io/test_imagestore.py
tests/unit/util/test_scanid.py

Refactor the way scan are stored:
- instead of generating a complex filename, `ImageStore` just uses `<jobid>/<scanid>.tiff`
- generate identifiers for scans that match the old image filename format (`<jobid>_<index>_<delta>`).
There is two advantages to doing it this way:
- the filename matches the id in API calls
- it should be more maintainable: we can change the way filenames (and ids) are generated without needing to rename all existing images.

Change the name of image files

---

Dockerfile

This makes it faster to rebuild the image by not rebuilding the ui if no ui file has changed.

Copy only what's necessary to build the ui in docker

---

scanomatic/ui_server_data/js/specs/api.spec.js
scanomatic/ui_server_data/js/specs/containers/ScanningRootContainer.spec.jsx
scanomatic/ui_server_data/js/specs/helpers.spec.js
scanomatic/ui_server_data/js/src/api.js
scanomatic/ui_server_data/js/src/containers/ScanningRootContainer.jsx
scanomatic/ui_server_data/js/src/helpers.js

- add function to get scanner job from API
- add helper function that get the list of scanner and their current
jobs from the API and builds a list of scanners with the `owned`
property as expected by the UI.

Get scanner "owned" property from API

---

scanomatic/scanning/update_scanner_status.py
scanomatic/util/datetime.py
tests/unit/scanning/test_update_scanner_status.py
tests/unit/util/test_datetime.py

Expose the following metrics to prometheus: `scanner_current_jobs`, `'scanner_queued_uploads`, `scanner_start_time_seconds`, `scanner_last_status_update_time_seconds`, `scanner_status_updates_total`. Each has a `scanner` label with the scanner id.
Some notes:
- Having a label with the scanner id sort-of goes againts prometheus instrumentation best practices as it's an unbounded dimension, at least in theory. But since those are important, it might be worth the extra disk usage. And it's not like we'll have millions of scanners...
- For somewhat similar reason, I added tests for the scanner metrics whereas we usually don't do that.
- The metrics don't expire: even if a scanner goes offline, scanomatic will expose the last value as long as it is not restarted. This means that prometheus …

Expose scanner metrics to prometheus

---

.travis.yml
tox.ini

This sends test coverage to codecov.io in addition to coveralls.
codecov.io has the ability to merge reports for a given build, which coveralls doesn't. This means we can divide the travis job in parts that can be run in parallel and be restarted individually (hopefully) and still have a unified coverage report.
My plan is to have both for some time, to build a baseline in codecov.io, before removing coveralls.

Publish test coverage to codecov.io

---

scanomatic/io/scanning_store.py
scanomatic/models/scan.py
scanomatic/scanning/update_scanner_status.py
scanomatic/ui_server/scan_jobs_api.py
scanomatic/ui_server/scanners_api.py
scanomatic/ui_server/scans_api.py
tests/integration/api/conftest.py
tests/integration/api/test_scanners.py
tests/unit/io/test_scanning_store.py

Remove duplication and simplify ScanningStore:
- `add_x(somex)` ➡ `add(somex)`
- `get_x(id)` ➡ `get(X, id)`
- `get_all_x()` ➡ `find(X)`
- `update_x(somex)` ➡ `update(somex)`
- `has_x(...)` ➡ `exists(X, ...)`
- etc.
Remove `get_free_scanners` and corresponding API parameter.
Methods for more specific queries/updates still exists (e.g. `get_current_job`).

Refactor ScanningStore interface

---

package.json

See webpack-contrib/karma-webpack#284 for background.

Unpin karma-webpack version

---

Dockerfile

installing package is expensive: make sure we only do it when necessary.

Make better use of the docker cache when building the ui

---

.travis.yml
tox.ini

This uses a beta feature on travis that allows splitting a build in
successive stages. (https://docs.travis-ci.com/user/build-stages/)
The build is split in two stages: first the (white box) tests, then
docker build and system tests.
Moreover, the tests are divided in two jobs: one running the python
tests and one running the javascript tests.
Given the overhead of setting up jobs on travis, dividing the build
doesn't really give us any speed boost but it makes it much nicer to
look at the result and allow restarting a single job.
On the other hand, the last thing I did was to remove the extra option
to `docker-compose build` and in the last two builds it went twice as
fast.  That's not a lot of data points but it'd be cool if it were to be
true :pray:
Some other relevant changes:
- this …

Split travis build in two stages

---

scanomatic/data_processing/calibration.py
scanomatic/io/ccc_data.py
scanomatic/models/factories/analysis_factories.py
scanomatic/models/factories/compile_project_factory.py
scanomatic/models/factories/scanning_factory.py
scanomatic/ui_server/calibration_api.py
scanomatic/ui_server/data_api.py
scanomatic/ui_server/ui_server.py
tests/unit/data_processing/test_calibration.py
tests/unit/models/factories/test_analysis_factory.py
tests/unit/ui_server/test_calibration_api.py

Refactor `scanomatic.data_processing.calibration` to remove the global `__CCC` global.
This doesn't really change the way it works: calibrations are still stored in an in-memory dictionary that is saved to disk explicitly in some of the functions. But instead of being a global dictionary, the calibration store is now encapsulated in a custom class (with dictionary-ish methods), passed to the calibration functions explicitly and referenced from the flask app.
A "store" is also created when needed in the different analysis jobs that used the `calibration` module.  If I understand thing correctly, this has the side benefits that it is no longer necessary to restart the backend when adding a new calibration.

Remove `__CCC` global

---

scanomatic/data_processing/calibration.py
tests/unit/data_processing/test_calibration.py
tests/unit/ui_server/test_calibration_api.py

Some more progress towards #147:
- remove the dictionary interface of `CalibrationStore` and replace it with more explicit methods
- start moving the responsibility of saving the CCCs to `CalibrationStore`. Only simple ones for now but I suspect that I'll want/need to do larger refactorings for the other ones so they can be separate PRs.
This is a refactoring, it is not intended to change the behavior at this point.

Start fleshing out the CalibrationStore interface

---

.travis.yml
tests/system/conftest.py

Upgrade the version of chromedriver in travis to 2.36.
This seems to solve the current build failure on master and on #314 but there are now selenium timeout errors on *some* runs.  I tried to increase the page load timeout without much success.
I ran the system tests job for 7c83605 ten times and I got five pass and five fails. On the other hand I didn't get a single *travis* timeout. I'm starting to think that this error is a different manifestation of the same thing that made the test suite hang and travis kill the job before. I don't know how to test this hypothesis though, if someone has an idea? (I did look into the release notes for chromedriver but didn't notice anything relevant).

Upgrade chromedriver

---

.travis.yml
scanomatic/data_processing/calibration.py
tests/system/conftest.py
tests/unit/data_processing/test_calibration.py

- Add a method to `CalibrationStore` to get all the measurements for a CCC.
- Add unit tests to the refactored use cases (`add_ccc`, `activate`ccc`, `delete_ccc` and `construct_polynomial`) that mock the calibration store.

Add one more method to CalibrationStore and proper unit tests for the refactored use-cases

---

.travis.yml
tests/conftest.py
tests/system/conftest.py

This makes the browser used in system tests a command line option and runs with firefox in travis.

Run system tests with firefox only

---

.travis.yml
scanomatic/data_processing/calibration.py
scanomatic/io/ccc_data.py
tests/system/conftest.py
tests/unit/data_processing/test_calibration.py

I think I have almost extracted a sufficient interface from `calibration.py` to put in a separate module that only deals with storing and retrieving data. The only thing remaining is adding measurements. The plan is then to implement this module using the database.
(Note: that's only the data that was in the `.ccc` file. Images and numpy arrays are still saved in files and not included in the `CalibrationStore` interface.)
I have manually tested creating and activating a "hanna" calibration with this.
The interface has become larger that I wanted to. I might be able to simplify it a by refactoring the way calibration works but that will require changing the API and the client code so I'll save it for later.
I could also split in stores for the different "types" (i.e. calibrations, images, …

Calibrationstore interface extraction

---

scanomatic/ui_server_data/js/specs/components/ScanningJobPanel.spec.jsx
scanomatic/ui_server_data/js/specs/components/ScanningRoot.spec.jsx
scanomatic/ui_server_data/js/specs/containers/ScanningRootContainer.spec.jsx
scanomatic/ui_server_data/js/src/components/ScanningJobPanel.jsx
scanomatic/ui_server_data/js/src/components/ScanningRoot.jsx
scanomatic/ui_server_data/js/src/containers/ScanningRootContainer.jsx
scanomatic/ui_server_data/style/experiment.css
tests/system/test_scanjob.py

- Adds some nice category labels to jobs.
- Adds a progress bar to running jobs
- Remakes the info about the job in to a nice table
- Adds sorting of jobs by category and then running by reverse chronological completion date and completed by reverse chronological started date.
- Makes the page live update every 10s

Start scan series labels and more

---

scanomatic/data/calibrationstore.py
scanomatic/data/migrations/versions/f9a3e426a0ce_create_calibrations_tables.py
tests/factories.py
tests/integration/data/test_calibrationstore.py

Add migration script to create the tables, `CalibrationStore` and integration tests.
I didn't change the data model itself: the information stored in the database is the same as what was in the `.ccc` files and with approximately the same structure.
The default calibration is added to the database directly as part of the migration. This makes the code simpler (no special cases) but the tests have to take it into account.

Add CalibrationStore implementatation using the database

---

scanomatic/data/scanjobstore.py
scanomatic/scanning/delete_scanjob.py
scanomatic/scanning/exceptions.py
scanomatic/scanning/terminate_scanjob.py
scanomatic/ui_server/scan_jobs_api.py
tests/integration/api/conftest.py
tests/integration/api/test_scanjobs.py
tests/integration/data/test_scanjobstore.py
tests/unit/scanning/test_delete_scanjob.py

Add API endpoint `DELETE /api/scan-jobs/$ID` that removes the scanjob from the database. It checks that the scanjob hasn't started yet.

Delete scanjob API

---

scanomatic/ui_server_data/js/specs/containers/NewScanningJobContainer.spec.jsx
scanomatic/ui_server_data/js/src/containers/NewScanningJobContainer.jsx

The React lifecycle method called when props are updated is named
`componentWillReceiveProps`, not `willRecieveNewProps`.

Bug fix in NewScanningJobContainer

---

tests/conftest.py
tests/system/conftest.py

Allow passing the url to a running scan-o-matic server and inhibit
starting docker-compose.
This makes working on system tests much quicker.

Add --scanomati-url option to tests

---

scanomatic/ui_server_data/js/specs/components/ScanningJobPanel.spec.jsx
scanomatic/ui_server_data/js/specs/components/ScanningJobPanelBody.spec.jsx
scanomatic/ui_server_data/js/specs/components/ScanningJobStatusLabel.spec.jsx
scanomatic/ui_server_data/js/specs/components/ScanningRoot.spec.jsx
scanomatic/ui_server_data/js/src/components/ScanningJobPanel.jsx
scanomatic/ui_server_data/js/src/components/ScanningJobPanelBody.jsx
scanomatic/ui_server_data/js/src/components/ScanningJobStatusLabel.jsx
scanomatic/ui_server_data/js/src/components/ScanningRoot.jsx
scanomatic/ui_server_data/js/src/containers/ScanningRootContainer.jsx
scanomatic/ui_server_data/style/experiment.css
tests/system/test_experiment_page.py

Integrate the changes from the previous PRs: #331, #333, and #335
Refactor `<ScanningJobPanel/>` to handle the job removing interaction:
- move the panel body in a separate component, `<ScannigJobPanelBody/>`
- add state to the panel to decide what is shown inside (normal body or
remove dialogue).
- move the status label logic in it's own component as well
Add system tests for removing scanning jobs.
*Note: I had to make the panel larger to accomodate the remove dialogue as provided in the UI mocks.*
Screenshots:
**step 1**
**step 2**
**Started jobs have no Remove button**

Delete UI integration

---

scanomatic/ui_server_data/js/src/components/ScanningJobPanel.jsx
tests/system/test_experiment_page.py

This fix the system tests that fails randomly by explicitely waiting for the job to appear after adding.
To avoid having to loop through the jobs all the time, I added the job name to the panel as a data attribute.

Add explicit wait when creating a job in system tests

---

scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.spec.jsx

Faking how it would look with proper bootstrap and overriding some of the `main.css` rules:
Implements a simple `ProjectPanel` and tests that it renders what it should render.

A simple project panel

---

.storybook/config.js
package.json
scanomatic/ui_server_data/js/src/components/NewProjectPanel.stories.jsx

One common and annoying problem that arise when working on react component is that it is sometime necessary to go through many hoops just to see how a component looks like. E.g. to see a running scanning job in scan-o-matic, one needs an online scanner, and then to create a job with the correct scanner and start it.
One possible solution is to temporarily insert a component with the desired state in the page but that's not very practical or elegant.  So my idea wast to build a static page with a collection of components in different states but of course, npm already has a tool for that, which is [storybook](https://storybook.js.org/).
It's exactly that: it lets you build a collection of components in different states but it adds some widgets for navigation, auto-reload, a console... (and …

Add storybook

---

karma.conf.js
scanomatic/ui_server_data/js/src/components/PolynomialConstruction.spec.jsx
scanomatic/ui_server_data/js/src/components/ProjectsRoot.jsx
scanomatic/ui_server_data/js/src/components/ProjectsRoot.spec.jsx
scanomatic/ui_server_data/js/src/helpers/jasmine-fail-on-console-error.js

This adds a spy on `console.error` that throw an exception. This mostly concerns prop types. That way, there's no need to scroll through the test results to look for error message (that don't even appear under the correct test). Instead, the test will fail.
Fix the existing errors.

Make jasmine fail on console.error

---

scanomatic/ui_server_data/js/src/components/NewExperimentPanel.jsx
scanomatic/ui_server_data/js/src/components/NewExperimentPanel.spec.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.stories.jsx
scanomatic/ui_server_data/js/src/prop-types.js

- Make `erros` a `Map` instead of an object
- Make the name of the scanner id more consistent with the prop name `scannerId`
(`scanner -> scannerId` in errors and in the callback)
- Add a valid option in the scanner drop down for when `scannerId` is
empty
- Leave sorting the scanners to the selector

Refactor <NewExperimentPanel/>

---

.travis.yml
README.md
tests/conftest.py
tests/system/conftest.py
tests/system/test_experiment_page.py
tox.ini

This adds an extra stage to the travis build that runs the system tests using saucelabs browsers.
* it is configured to use two browser: Firefox and Chrome, both on windows (the available browsers on Linux are lagging behind quite a bit :disappointed:).
* It will only run on push to master.  There are a few reason for this: the credentials are not available on external pull requests ; I want to make sure it's not too flaky ; and more importantly, it takes 20 minutes to run :fearful:

Run system test using sauce labs on travis

---

scanomatic/ui_server_data/js/src/components/NewExperimentPanel.stories.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.stories.jsx
scanomatic/ui_server_data/js/src/components/ProjectsRoot.jsx
scanomatic/ui_server_data/js/src/components/ProjectsRoot.spec.jsx
scanomatic/ui_server_data/js/src/containers/ProjectsRootContainer.jsx
scanomatic/ui_server_data/js/src/projects/index.jsx
scanomatic/ui_server_data/js/src/projects/reducers/entities/index.js
scanomatic/ui_server_data/js/src/projects/reducers/entities/scanners.js
scanomatic/ui_server_data/js/src/projects/reducers/entities/scanners.spec.js
scanomatic/ui_server_data/js/src/projects/selectors.js
scanomatic/ui_server_data/js/src/projects/selectors.spec.js
tests/system/test_projects_page.py

This connects all the new components to the state:
- sets the `newExperiment*` props in the appropriate components
- render `<ExperimentPanel/>`s for each projects' experiment.
- add system tests that create new experiments
Refactor `<ProjectPanel/>`: instead of rendering the (new) experiment in the `<ProjectPanel/>` componenet, they are passed as children. This makes the component much simpler and avoid passing a gazillion props through.

Extends <ProjectsRootContainer/> to allow adding experiments

---

scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.jsx
scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx
scanomatic/ui_server_data/style/project.css

Margin below the `+ Add Experiment` button and having the status label to the right again.

Stylefixes

---

.flowconfig

This test-file causes error in flow. I wasn't sure if it was good idea to omit entire `node_modules` since it might be useful if we use modules that use flow too.

Flow config

---

scanomatic/ui_server/templates/qc_norm.html
scanomatic/ui_server_data/js/qc_normHelper.js
tests/system/test_qcnorm.py

- Left/right buttons now behave as expected.
- Q-index is shown in the UI
- Added button to go to first Q-index

Fixed left/right arrow buttons in QC

---

scanomatic/ui_server/templates/qc_norm.html
scanomatic/ui_server_data/js/src/qc/QIndexAndSelectionIntegration.js
scanomatic/ui_server_data/style/qc_norm.css
tests/system/test_qcnorm.py

Replaced panel showing current qindex with an input box, and re-purposed the reset-button as a set-button.
Since the "hot keys" for switching plates interfered with using the input in a natural way, I removed those.

Qindex input box
