.idea/workspace.xml, scanomatic/generics/abstract_model_factory.py, scanomatic/generics/model.py, scanomatic/models/analysis_model.py, scanomatic/models/compile_project_model.py, scanomatic/models/factories/compile_project_factory.py, scanomatic/models/features_model.py, scanomatic/models/rpc_job_models.py, scanomatic/models/scanning_model.py, scanomatic/server/scanning_effector.py
Updated models so they support pycharm field hinting
=> Models hinting

data/ui_server/fixture.html, data/ui_server/js/fixtures.js, data/ui_server/js/grayscales.js, data/ui_server/js/helpers.js
resolved issue with scrolled window in chrome and safari.
moved js code so files becomes more relevant in size and category
prototyped ways of having more flexible html <-> js interaction
=> Cleaned up ui-server stuff

scanomatic/io/sane.py
it scanning fails the file is removed instead of leaving an empty file.
=> Fixes crashed scans issue

scanomatic/generics/abstract_model_factory.py, scanomatic/models/factories/analysis_factories.py, scanomatic/models/factories/compile_project_factory.py, scanomatic/models/factories/features_factory.py, scanomatic/models/factories/fixture_factories.py, scanomatic/models/factories/rpc_job_factory.py, scanomatic/models/factories/scanning_factory.py, scanomatic/models/scanning_model.py
Cleaning up factories and serialization to output nicer data.
As an implication, updating models and factories.
To fulfill need of analysis, the scanning-model system restructured.
=> Backtracking to structure models and factories better

dev/unittests/unit_test_resources.py, scanomatic/generics/abstract_model_factory.py, scanomatic/generics/model.py, scanomatic/imageAnalysis/grid_array.py, scanomatic/imageAnalysis/imageGrayscale.py, scanomatic/io/mail.py, scanomatic/models/factories/scanning_factory.py, scanomatic/models/scanning_model.py, scanomatic/server/analysis_effector.py, scanomatic/server/interface_builder.py, scanomatic/server/proc_effector.py, scanomatic/server/scanning_effector.py
Improves grayscale detection and validification and extends emailing abilities.
=> Grayscale, analysis and emails

postSetup.py
Fixed so that failing to install linux launcher gives nice output and switched to not testing for 'posix' but for actual os-type.
=> Post setup bug

scanomatic/util/__init__.py, scanomatic/util/legacy_compatibility.py, setup.py
Added util submodule which currently includes a legacy compatibility to take early developmental projects into current regime. 
Current functionality is to rewrite file-names so that they get approximated time-stamps written into their names.
=> Util submodule

scanomatic/imageAnalysis/grid_array.py, scanomatic/imageAnalysis/grid_cell.py, scanomatic/io/image_data.py, scanomatic/io/paths.py, scanomatic/io/xml/writer.py
Saving out the resulting grid numpy arrays.
Fixed sorting along the longest dimension.
=> Colony sorting and gridding

.travis.yml
test-requirements are installed in tox.
=> Remove unecessary pip install in travis

requirements.in, requirements.txt, scanomatic/ui_server/ui_server.py, scripts/scan-o-matic
Luciano requested that we allow CORS while running in debug mode. This opens up for http://en.wikipedia.org/wiki/Cross-site_request_forgery but given that it is only active in debug I think it should be OK.
=> CORS in debug mode

scanomatic/image_analysis/grid_array.py, scanomatic/image_analysis/grid_cell.py, scanomatic/image_analysis/test/test_grid_array.py, scanomatic/image_analysis/test/test_grid_cell_extra.py, scanomatic/ui_server/calibration_api.py
We currently know that this has issues, but I am creating a pull request nonetheless to get the proper review process started. Will look at the reported problem and see if I can fix it, but meanwhile would appreciate if someone would look at the changes not directly related to the grid API.
=> Issue 133 set gridding outputs confusing

scanomatic/models/factories/settings_factories.py
Caused error trying to copy models since serialization was looking
for attribute local on the model which was no longer there
Also made lines shorter
=> Removed 'local' in factory since it is no longer in model

scanomatic/ui_server_data/CCC.html, scanomatic/ui_server_data/access_restricted.html, scanomatic/ui_server_data/analysis.html, scanomatic/ui_server_data/compile.html, scanomatic/ui_server_data/experiment.html, scanomatic/ui_server_data/feature_extract.html, scanomatic/ui_server_data/fixture.html, scanomatic/ui_server_data/help.html, scanomatic/ui_server_data/maintain.html, scanomatic/ui_server_data/qc_norm.html, scanomatic/ui_server_data/status.html
I found the UI code very hard to navigate, so I reformatted the HTML
code.  There should be no functional changes.
=> Updated formatting in HTML files

scanomatic/generics/abstract_model_factory.py, scanomatic/generics/test/test_abstract_model_factory.py, scanomatic/models/factories/analysis_factories.py, scanomatic/models/factories/compile_project_factory.py, scanomatic/models/factories/scanning_factory.py, scanomatic/models/factories/test/test_analysis_factory.py, scanomatic/models/factories/test/test_scanning_factory.py, scanomatic/models/scanning_model.py, scanomatic/server/compile_effector.py, scanomatic/server/scanning_effector.py, scanomatic/ui_server/ui_server.py, scanomatic/ui_server_data/experiment.html, scanomatic/ui_server_data/js/analysis.js, scanomatic/ui_server_data/js/experiment.js
Passing CCC information along from experiment -> job -> compile -> analysis.
- Could probably do with more tests. Help with this would be appreciated.
- I have not taken care of lint complaints to any great extent. I  am planning on doing this in a separate PR for the affected files once this is accepted.
=> Experiment UI includes and passes CCC to backend

scanomatic/models/compile_project_model.py, scanomatic/ui_server/ui_server.py
- `CompileInstructionsModel` needed `cell_count_calibration_id` argument and attribute.
- `add_base_routes` in `ui_server.py` needed `rpc_client`
=> Fixed missed details

scanomatic/data_processing/calibration.py, scanomatic/data_processing/test/test_calibration.py
Found an error from previous refactoring that wasn't complete. Fixed and wrote some tests for it.
=> Calibration save error

setup.py
=> removed install launcher and added install_data_files

.editorconfig
Copied from the EONav repository. Feel free to suggest changes.
=> Add editorconfig to make indentation consistent

karma.conf.js, package.json, scanomatic/ui_server_data/js/ccc.js, scanomatic/ui_server_data/js/specs/ccc.spec.js
Reset the callbacks on the re-gridding button before re-adding.
=> Fix duplicate request regridding

scanomatic/ui_server_data/js/ccc/components/ColonyEditor.js, scanomatic/ui_server_data/js/ccc/containers/ColonyEditorContainer.js, scanomatic/ui_server_data/js/specs/components/ColonyEditor.spec.js, scanomatic/ui_server_data/js/specs/containers/ColonyEditorContainer.spec.js
Allow the user to skip a colony they aren't interested in during CCC.
=> Add "Skip" button in colony editor

karma.conf.js, scanomatic/ui_server_data/js/ccc/api.js, scanomatic/ui_server_data/js/ccc/index.js, scanomatic/ui_server_data/js/specs/api.spec.js, scanomatic/ui_server_data/js/specs/ccc.spec.js
- return ES6 promises
- remove `scope` from the passed arguments
- add unit tests
- factor common code
=> Refactor JS API functions related to uploading images

scanomatic/ui_server_data/js/ccc/components/ImageUpload.js, scanomatic/ui_server_data/js/ccc/containers/ImageUploadContainer.js, scanomatic/ui_server_data/js/ccc/helpers.js, scanomatic/ui_server_data/js/specs/components/ImageUpload.spec.js, scanomatic/ui_server_data/js/specs/containers/ImageUploadContainer.spec.js, scanomatic/ui_server_data/js/specs/helpers.spec.js
- Update <ImageUpload /> to show a progress bar
- Update <ImageUploadContainer /> to update <ImageUpload /> progress
- Update uploadImage() helper to set progress using a callback
=> Display upload progress when adding image to CCC

scanomatic/ui_server_data/js/ccc/containers/ImageUploadContainer.js, scanomatic/ui_server_data/js/specs/containers/CCCEditorContainer.spec.js, scanomatic/ui_server_data/js/specs/containers/ImageUploadContainer.spec.js, scanomatic/ui_server_data/js/specs/helpers/FakePromise.js
Reset the component when upload finishes.
=> Fix upload progress

karma.conf.js, webpack.config.js
=> Configure webpack and karma for `.jsx` files

scanomatic/ui_server_data/js/ccc/components/CCCEditor.js
=> Fix key in <CCCEditor />

scanomatic/data_processing/calibration.py, scanomatic/data_processing/test/test_calibration.py, scanomatic/ui_server/calibration_api.py, scanomatic/ui_server/test/test_calibration_api.py, scanomatic/ui_server_data/js/ccc/containers/PolynomialConstructionContainer.js, scanomatic/ui_server_data/js/specs/containers/PolynomialConstructionContainer.spec.js
Bit restructure to allow better testing and return more information from the polynomial construction
=> Ccc calibration update

scanomatic/ui_server_data/js/ccc/components/PolynomialConstruction.js, scanomatic/ui_server_data/js/ccc/components/PolynomialResultsInfo.js, scanomatic/ui_server_data/js/ccc/containers/PolynomialConstructionContainer.js, scanomatic/ui_server_data/js/specs/components/PolynomialConstruction.spec.js, scanomatic/ui_server_data/js/specs/containers/PolynomialConstructionContainer.spec.js
- Use bootstrap inline form to arrange the select and the button
- Add a "degree of polynomial" label
- pass the selected degree to the api
- available values are 1 to 5 but that's easy to change
=> Add a <select /> to choose the degree of the polynomial

scanomatic/ui_server_data/js/ccc/components/ColonyFeatures.jsx, scanomatic/ui_server_data/style/ccc.css
Make the two canvas align in the CCC editor and move the feature legend to the right of the canvas.
=> Align colony canvas

.travis.yml
Don't know if this is the way to do it :)
=> Triggering jenkins on merge

scanomatic/ui_server/scan_jobs_api.py, scanomatic/ui_server/scanners_api.py, tests/integration/api/test_scanners.py, tests/system/test_analysis.py, tests/unit/ui_server/test_scan_jobs_api.py, tests/unit/ui_server/test_scanners_api.py, tox.ini
This also converts the tests to integration tests.
=> Fix an error in the endpoint to get a scanner job

scanomatic/io/scanning_store.py, tests/unit/io/test_scanning_store.py, tests/unit/ui_server/test_scanners_api.py
:fax: :battery: :+1:
Also adding ability to hide test scanners via `os.environ`.
Added test for this hiding.
=> Adding another test scanner that is always on

.stickler.yml
This would allow stickler-ci to do, or propose? automatic fixing of js-errors.
=> Automatic fixing of js-errors

scanomatic/util/birds.txt, scanomatic/util/generic_name.py, setup.py
More robust way to access data files in a python package.
=> Fix name generator

scanomatic/io/scanning_store.py, scanomatic/ui_server/scanners_api.py, tests/unit/io/test_scanning_store.py, tests/unit/ui_server/test_scanners_api.py
I've added tests for the `scanning_store` methods, but I suspect that there are tests missing for the API endpoint. I'll have a look first myself, but please tell me if you spot anything obvious that I've missed.
=> Get status tests

tests/conftest.py, tests/integration/test_analysis_effector.py, tests/unit/image_analysis/test_grid.py, tests/unit/image_analysis/test_grid_array.py
* Mark slow unit and integration tests 
* Add --skip-slow option to skip slow tests
=> Mark slow tests

scanomatic/io/scanning_store.py, scanomatic/models/scanner.py, scanomatic/scanning/update_scanner_status.py, scanomatic/ui_server/scanners_api.py, setup.py, tests/integration/api/test_scanners.py, tests/unit/io/test_scanning_store.py
* Move the `Scanner` class in the `scanomatic.models` package
* Create package `scanomatic.scanning` to hold domain logic related to scanning
* Move domain logic related to scanner status update in module `scanomatic.scanning.update_scanner_status`.
=> Refactoring update scanner status

.gitignore, scanomatic/models/scannerstatus.py, scanomatic/scanning/update_scanner_status.py, scanomatic/ui_server/scanners_api.py, scanomatic/ui_server/serialization.py, tests/integration/api/test_scanners.py, tests/system/test_compile_scanjob.py, tests/unit/io/test_scanning_store.py, tests/unit/scanning/test_update_scanner_status.py
https://github.com/Scan-o-Matic/scanomatic-scanner/pull/17
=> server side of keepalive status scanomatic-scanning pr17

Dockerfile, setup.py
- remove everything but `setup()`
- use setuptools' `find_packages()` to automatically build the list of packages.
=> Simplify setup.py

scanomatic/ui_server_data/js/specs/components/ScanningJobRemoveButton.spec.jsx, scanomatic/ui_server_data/js/specs/components/ScanningJobRemoveDialogue.spec.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobRemoveButton.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobRemoveDialogue.jsx
`<ScanningJobRemoveButton/>`
`<ScanningJobRemoveDialogue/>`
=> Add <ScanningJobRemoveButton/> and <ScanningJobRemoveDialogue/>

scanomatic/ui_server_data/js/specs/Duration.spec.js, scanomatic/ui_server_data/js/specs/api.spec.js, scanomatic/ui_server_data/js/specs/components/ScanningJobPanel.spec.jsx, scanomatic/ui_server_data/js/specs/components/ScanningJobPanelBody.spec.jsx, scanomatic/ui_server_data/js/specs/components/ScanningJobStopButton.spec.jsx, scanomatic/ui_server_data/js/specs/components/ScanningJobStopDialogue.spec.jsx, scanomatic/ui_server_data/js/specs/components/ScanningRoot.spec.jsx, scanomatic/ui_server_data/js/specs/containers/NewScanningJobContainer.spec.jsx, scanomatic/ui_server_data/js/specs/containers/ScanningRootContainer.spec.jsx, scanomatic/ui_server_data/js/src/Duration.js, scanomatic/ui_server_data/js/src/api.js, scanomatic/ui_server_data/js/src/components/ScanningJobPanel.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobPanelBody.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobStatusLabel.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobStopButton.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobStopDialogue.jsx, scanomatic/ui_server_data/js/src/components/ScanningRoot.jsx, scanomatic/ui_server_data/js/src/containers/ScanningRootContainer.jsx, scanomatic/ui_server_data/js/src/prop-types.js, tests/system/test_experiment_page.py
Similar to the previous PRs but for stopping running jobs.
=> Stop Job UI

scanomatic/util/generic_name.py, tests/system/test_scanner.py, tests/unit/util/test_generic_name.py
No :tea: no more in the scanner names.
:smile:
=> Scanner names without THE

scanomatic/io/app_config.py
Clean up.
If there needs to be actual settings in the future, the should go into a db.
Currently there would never be any settings written to file, because only ever defaults would be used. Except for the admin uuid for requesting stuff from the `scanomatic-backend` however this too really didn't fulfill any useful functionality at the moment since both are launched within the same docker network.
Tested by existing tests & manually making a compilation and analysis.
=> Remove all disk IO from app settings

scanomatic/ui_server_data/js/specs/components/FinalizedCCC.spec.jsx, scanomatic/ui_server_data/js/src/components/FinalizedCCC.jsx
This will load the default view (currently the status-view).
Resolves #318
=> Updated the link

scanomatic/ui_server_data/js/specs/components/NewProjectPanel.spec.jsx, scanomatic/ui_server_data/js/src/components/NewProjectPanel.jsx
=> Add <NewProjectPanel/> component

scanomatic/ui_server/templates/projects.html, scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.spec.jsx, scanomatic/ui_server_data/js/src/components/ProjectsRoot.jsx, scanomatic/ui_server_data/js/src/components/ProjectsRoot.spec.jsx, scanomatic/ui_server_data/js/src/prop-types.js, scanomatic/ui_server_data/style/project.css
* Lists projects in the order it gets them
* New Project button and its form/panel.
=> ProjectsRoot displays more stuff

scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.spec.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.stories.jsx
=> Project new experiment

scanomatic/ui_server_data/js/src/components/NewProjectPanel.jsx, scanomatic/ui_server_data/js/src/components/NewProjectPanel.stories.jsx, scanomatic/ui_server_data/js/src/components/ProjectsRoot.jsx
The component now expects a `Map` of errors, and it renders like this:
=> Update <NewProjectPanel/> to show errors per field

scanomatic/ui_server_data/js/src/Duration.js, scanomatic/ui_server_data/js/src/Duration.spec.js, scanomatic/ui_server_data/js/src/api.js, scanomatic/ui_server_data/js/src/api.spec.js, scanomatic/ui_server_data/js/src/components/DurationInput.jsx, scanomatic/ui_server_data/js/src/components/DurationInput.spec.jsx, scanomatic/ui_server_data/js/src/components/DurationInput.stories.jsx, scanomatic/ui_server_data/js/src/components/NewScanningJob.jsx, scanomatic/ui_server_data/js/src/components/NewScanningJob.spec.jsx, scanomatic/ui_server_data/js/src/containers/NewScanningJobContainer.jsx, scanomatic/ui_server_data/js/src/containers/NewScanningJobContainer.spec.jsx, scanomatic/ui_server_data/js/src/containers/ScanningRootContainer.jsx
I tested that it worked with the scan-jobs ui manually too.
=> Duration input

scanomatic/ui_server_data/js/src/projects/StateBuilder.js, scanomatic/ui_server_data/js/src/projects/actions.js, scanomatic/ui_server_data/js/src/projects/actions.spec.js, scanomatic/ui_server_data/js/src/projects/selectors.js, scanomatic/ui_server_data/js/src/projects/selectors.spec.js
Add `getScanner` selector and `submitNewExperiment` action.
=> Projects page store: add getScanners and submitExperiment

scanomatic/ui_server_data/js/src/components/NewExperimentPanel.jsx, scanomatic/ui_server_data/js/src/components/NewExperimentPanel.spec.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.stories.jsx, scanomatic/ui_server_data/js/src/prop-types.js, scanomatic/ui_server_data/style/project.css
=> Project new experiment panel

scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.jsx, scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.spec.jsx, scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.stories.jsx, scanomatic/ui_server_data/js/src/components/ScanningJobPanelBody.jsx, scanomatic/ui_server_data/js/src/prop-types.js, scanomatic/ui_server_data/style/project.css
=> Basic panel with story and test

scanomatic/ui_server_data/js/src/projects/index.jsx, scanomatic/ui_server_data/js/src/projects/reducers/entities/index.js, scanomatic/ui_server_data/js/src/projects/reducers/entities/scanners.js, scanomatic/ui_server_data/js/src/projects/reducers/entities/scanners.spec.js
Add a dummy scanner reducer and add a scanner in the initial state. This is for testing the new experiment form.
=> Add dummy scanner reducer

scanomatic/ui_server_data/js/src/components/ProjectPanel.spec.jsx, scanomatic/ui_server_data/js/src/components/ProjectPanel.stories.jsx, scanomatic/ui_server_data/js/src/components/ProjectsRoot.jsx, scanomatic/ui_server_data/js/src/components/ProjectsRoot.spec.jsx, tests/system/test_projects_page.py
Most recent experiment in a project and most recent project are default expanded.
=> Default expand firsts

scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.jsx, scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.spec.jsx, scanomatic/ui_server_data/js/src/components/ExperimentPanel/index.stories.jsx, scanomatic/ui_server_data/js/src/containers/ProjectsRootContainer.jsx, scanomatic/ui_server_data/js/src/projects/actions.js, scanomatic/ui_server_data/js/src/projects/actions.spec.js, scanomatic/ui_server_data/js/src/projects/reducers/entities/experiments.js, scanomatic/ui_server_data/js/src/projects/reducers/entities/experiments.spec.js, scanomatic/ui_server_data/js/src/projects/selectors.js, scanomatic/ui_server_data/js/src/projects/selectors.spec.js
=> Fixed ending/ended/planned end and showing reason

.gitignore, Dockerfile, scanomatic/ui_server/templates/status.html, scanomatic/ui_server_data/js/src/components/ScannerStatus.spec.jsx, scanomatic/ui_server_data/js/src/components/ScannersStatus.jsx, scanomatic/ui_server_data/js/src/components/ScannersStatus.stories.jsx, scanomatic/ui_server_data/js/src/components/StatusRoot.jsx, scanomatic/ui_server_data/js/src/containers/StatusRootContainer.jsx, scanomatic/ui_server_data/js/src/statuspage/StateBuilder.js, scanomatic/ui_server_data/js/src/statuspage/actions.js, scanomatic/ui_server_data/js/src/statuspage/actions.spec.js, scanomatic/ui_server_data/js/src/statuspage/index.jsx, scanomatic/ui_server_data/js/src/statuspage/reducers/experiments.js, scanomatic/ui_server_data/js/src/statuspage/reducers/experiments.spec.js, scanomatic/ui_server_data/js/src/statuspage/reducers/index.js, scanomatic/ui_server_data/js/src/statuspage/reducers/scanners.js, scanomatic/ui_server_data/js/src/statuspage/reducers/scanners.spec.js, scanomatic/ui_server_data/js/src/statuspage/reducers/updateStatus.js, scanomatic/ui_server_data/js/src/statuspage/reducers/updateStatus.spec.js, scanomatic/ui_server_data/js/src/statuspage/selectors.js, scanomatic/ui_server_data/js/src/statuspage/selectors.spec.js, scanomatic/ui_server_data/js/src/statuspage/state.js, scanomatic/ui_server_data/style/status.css, webpack.config.js
Added react to status page, added a store and connected with existing api and the new scanners status component.
=> New scanner status integrated

tests/system/test_qcnorm.py
Reusing fixtures in all tests.
I'm a bit uncertain about the `page_no_analysis` fixture, since it is only used once, but I added it to make the code more uniform, in the hope that it makes it clearer over all.
=> Using fixtures in all qc system tests

scanomatic/ui_server_data/js/qc_normHelper.js, tests/system/test_qcnorm.py
QIndex is now updated when a colony is selected by clicking on the plate, magic interactions a little bit less magical.
=> update qindex when clicking a colony

.travis.yml, README.md
This disables saucelabs testing... :-(
=> disabled Saucelab ;-(

README.md
Maybe add codecov badge as well?
=> Added requirements badge

requirements.txt, scan-requirements.txt
Only python requirements, not js...
=> Update python requirements
